#!/usr/bin/perl

use strict;

use Nagios::Plugin;

use LWP::UserAgent;
use Mojo::DOM;
use Switch;
use Config::IniFiles;


my $np = Nagios::Plugin->new(  
     usage => "Usage: %s  "
       . "[ -c|--critical=<threshold> ] [ -w|--warning=<threshold> ] -l|--login <login> -f|--conf <path-to-ini>",
   );   

   $np->add_arg(
     spec => 'critical|c=s',
     help => '-c, --critical=INTEGER:INTEGER .  See '
       . 'http://nagiosplug.sourceforge.net/developer-guidelines.html#THRESHOLDFORMAT '
       . 'for the threshold format. ',
   );
   $np->add_arg(
     spec => 'warning|w=s',
     help => '-w, --warning=INTEGER:INTEGER .  See '
       . 'http://nagiosplug.sourceforge.net/developer-guidelines.html#THRESHOLDFORMAT '
       . 'for the threshold format. ',
   );
   $np->add_arg(
     spec => 'login|l=s',
     help => '-l, --login=LOGIN .   '
       . 'youmagic login '
       . 'for the threshold format. ',
   );
   $np->add_arg(
     spec => 'conf|f=s',
     help => '-f, --conf=PATH Path to ini-file with passwords '
   );

   $np->getopts;

my $cfg = new Config::IniFiles( -file => $np->opts->conf ) || $np->nagios_exit( UNKNOWN, "Unable to read config at ".$np->opts->conf) ;

my $login = $np->opts->login;
my $password = $cfg->val( 'zadarma', "password_$login" );

my $ua = LWP::UserAgent->new(cookie_jar => { file => "/tmp/.cookies.$$.txt" });


push @{ $ua->requests_redirectable }, 'POST';
my $response = $ua->post( 'https://ss.zadarma.com/auth/login/', {email => $login, password => $password} );
my $dom = Mojo::DOM->new($response->decoded_content);
my $errormsg = $dom->find("p.error")->[0];
$np->nagios_exit( UNKNOWN, "Login failed: ".$errormsg->text) if $errormsg;

my $response = $ua->get( 'https://ss.zadarma.com/' );
$dom = Mojo::DOM->new($response->decoded_content);

my $balancespan = $dom->find("span.balance")->[0]->text;
my ($balance) = ( $balancespan =~ /\$(\d+\.\d+)/);
$np -> add_perfdata( label =>"balance", value =>  $balance , threshold => 0 );

  $np->nagios_exit(
        return_code => $np->check_threshold($balance),
        message     => "Balance is $balance"
  );


END { unlink("/tmp/.cookies.$$.txt"); }

